/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3-dev */

#include "domopool.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(domopool_NTP, domopool_NTP, AUTO)

PB_BIND(domopool_Mqtt, domopool_Mqtt, AUTO)

PB_BIND(domopool_Network, domopool_Network, 2)

PB_BIND(domopool_Temp, domopool_Temp, AUTO)

PB_BIND(domopool_AnalogSensor, domopool_AnalogSensor, AUTO)

PB_BIND(domopool_Sensors, domopool_Sensors, AUTO)

PB_BIND(domopool_Global, domopool_Global, AUTO)

PB_BIND(domopool_Time, domopool_Time, AUTO)

PB_BIND(domopool_Pump, domopool_Pump, AUTO)

PB_BIND(domopool_Alarms, domopool_Alarms, AUTO)

PB_BIND(domopool_Tests, domopool_Tests, AUTO)

PB_BIND(domopool_Metrics, domopool_Metrics, AUTO)

PB_BIND(domopool_States, domopool_States, AUTO)

PB_BIND(domopool_Config, domopool_Config, 2)

#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif
